services:
  laced-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
    expose:
      - 5432
  laced-app:
    build: .
    ports:
      - "8001:8000"
    env_file:
      - ".env"
    depends_on:
      - laced-db
    command: sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --clear --noinput &&
      python manage.py loaddata
      core/fixtures/data.json &&
      python manage.py runserver 0.0.0.0:8000"
    restart: on-failure